"""Security headers: what we tell the browser it may do with our responses."""

import re
from collections.abc import Iterator

import pytest
from fastapi.testclient import TestClient

from app.core import security_headers
from app.core.rate_limit import limiter
from app.core.security_headers import (
    API_CSP,
    BASE_HEADERS,
    DOCS_CSP,
    HSTS,
    is_https_environment,
    policy_for,
)
from app.main import app

# Any absolute origin referenced by a served page.
ORIGIN = re.compile(r"https://[a-zA-Z0-9.-]+")


@pytest.fixture
def client() -> Iterator[TestClient]:
    limiter.reset()
    try:
        yield TestClient(app)
    finally:
        limiter.reset()


# --- the headers every response carries -----------------------------------


@pytest.mark.parametrize(("header", "value"), sorted(BASE_HEADERS.items()))
def test_every_response_carries_the_base_headers(client, header, value):
    response = client.get("/healthz")

    assert response.headers[header] == value


def test_an_error_response_carries_them_too(client):
    """The middleware sits outside the others, so it reaches their answers."""
    response = client.get("/no-such-route")

    assert response.status_code == 404
    assert response.headers["x-content-type-options"] == "nosniff"
    assert response.headers["content-security-policy"] == API_CSP


def test_a_refused_body_still_carries_them(client):
    """A 413 is generated by middleware, not by a route."""
    response = client.post("/api/v1/auth/otp/request", content=b"x" * (2 * 1024 * 1024))

    assert response.status_code == 413
    assert response.headers["x-frame-options"] == "DENY"
    assert response.headers["content-security-policy"] == API_CSP


# --- the two policies -----------------------------------------------------


def test_json_gets_the_strictest_possible_policy(client):
    """A JSON API loads nothing, so it is allowed to load nothing."""
    response = client.get("/healthz")

    assert response.headers["content-security-policy"] == API_CSP
    assert "default-src 'none'" in API_CSP


@pytest.mark.parametrize("path", ["/docs", "/redoc"])
def test_the_docs_pages_get_the_wider_policy(client, path):
    response = client.get(path)

    assert response.status_code == 200
    assert response.headers["content-security-policy"] == DOCS_CSP


@pytest.mark.parametrize("path", ["/docs", "/redoc"])
def test_the_docs_policy_covers_what_the_page_actually_loads(client, path):
    """The regression guard.

    If a FastAPI upgrade moves Swagger UI or ReDoc to a different CDN, the
    policy would silently block it and the API documentation would break.
    This reads the markup we really serve and checks every origin in it is
    allowed.

    It can only see what is in the HTML: today that is cdn.jsdelivr.net,
    fastapi.tiangolo.com and, for ReDoc, fonts.googleapis.com. The font
    files themselves come from fonts.gstatic.com, referenced from inside
    that stylesheet, so the policy allows it although this test cannot see
    it.
    """
    html = client.get(path).text
    origins = {match.group(0) for match in ORIGIN.finditer(html)}

    assert origins, "expected the page to reference at least one CDN"
    for origin in origins:
        assert origin in DOCS_CSP, f"{origin} is loaded by {path} but not allowed"


def test_the_docs_policy_allows_the_inline_bootstrap_script(client):
    """FastAPI writes an inline <script> to start the viewer, and we do not
    control that markup. If it ever stops being inline, tighten the policy."""
    html = client.get("/docs").text

    assert "<script>" in html
    assert "'unsafe-inline'" in DOCS_CSP


def test_the_api_policy_never_allows_inline_anything():
    assert "unsafe-inline" not in API_CSP
    assert "unsafe-eval" not in API_CSP


@pytest.mark.parametrize(
    ("path", "expected"),
    [
        ("/docs", DOCS_CSP),
        ("/redoc", DOCS_CSP),
        ("/healthz", API_CSP),
        ("/api/v1/campaigns", API_CSP),
        ("/docs/oauth2-redirect", API_CSP),
        ("", API_CSP),
    ],
)
def test_the_policy_is_chosen_by_path(path, expected):
    assert policy_for(path) == expected


# --- HSTS -----------------------------------------------------------------


def test_hsts_is_not_sent_locally(client):
    """Sending it for localhost forces HTTPS on every other local project on
    the machine, and only a manual browser reset undoes it."""
    response = client.get("/healthz")

    assert "strict-transport-security" not in response.headers


def test_hsts_is_sent_once_deployed(client, monkeypatch):
    monkeypatch.setattr(security_headers, "is_https_environment", lambda: True)

    response = client.get("/healthz")

    assert response.headers["strict-transport-security"] == HSTS


@pytest.mark.parametrize(
    ("environment", "expected"),
    [("local", False), ("test", False), ("staging", True), ("production", True)],
)
def test_https_is_assumed_everywhere_but_local(monkeypatch, environment, expected):
    monkeypatch.setattr(security_headers.settings, "environment", environment)

    assert is_https_environment() is expected


def test_hsts_does_not_ask_for_preload():
    """Preload is baked into browsers and slow to undo, so it is a founder
    decision, not a default."""
    assert "preload" not in HSTS


# --- leaving deliberate choices alone -------------------------------------


def test_a_header_a_route_already_set_is_not_overwritten():
    from fastapi import FastAPI
    from fastapi.responses import JSONResponse

    from app.core.security_headers import SecurityHeadersMiddleware

    other = FastAPI()
    other.add_middleware(SecurityHeadersMiddleware)

    @other.get("/framed")
    def framed() -> JSONResponse:
        return JSONResponse({"ok": True}, headers={"X-Frame-Options": "SAMEORIGIN"})

    response = TestClient(other).get("/framed")

    assert response.headers["x-frame-options"] == "SAMEORIGIN"
    # The ones it did not set are still applied.
    assert response.headers["x-content-type-options"] == "nosniff"
