"""add admin role, suspension, reports and admin log (D-061)

Alembic does not compare CHECK constraints, so the account checks are written
by hand: the role check widens to admit 'admin', and suspension must always
carry a reason. The admin log is append-only through the general trigger
function the checkpoint migration created.

The downgrade refuses while any admin account exists: narrowing the role
check under one would fail halfway, or worse, leave an account whose role
nothing recognises.

Revision ID: 0942f3ef82c3
Revises: 18aa2bc4cc78
Create Date: 2026-09-27 15:10:33.128809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0942f3ef82c3'
down_revision: Union[str, None] = '18aa2bc4cc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('admin_account_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('subject_account_id', sa.UUID(), nullable=True),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('view_account', 'suspend', 'restore', 'resolve_report')", name=op.f('ck_admin_action_action_allowed')),
    sa.CheckConstraint('note IS NULL OR char_length(note) <= 1000', name=op.f('ck_admin_action_note_length')),
    sa.ForeignKeyConstraint(['admin_account_id'], ['account.id'], name=op.f('fk_admin_action_admin_account_id_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_action'))
    )
    op.create_index('ix_admin_action_created_at', 'admin_action', ['created_at'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('reporter_account_id', sa.UUID(), nullable=False),
    sa.Column('subject_kind', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'open') = (resolved_at IS NULL)", name=op.f('ck_report_resolved_when_closed')),
    sa.CheckConstraint("category IN ('fake_profile', 'spam', 'abuse', 'non_payment', 'other')", name=op.f('ck_report_category_allowed')),
    sa.CheckConstraint("status IN ('open', 'actioned', 'dismissed')", name=op.f('ck_report_status_allowed')),
    sa.CheckConstraint("subject_kind IN ('creator', 'brand', 'campaign')", name=op.f('ck_report_subject_kind_allowed')),
    sa.CheckConstraint('note IS NULL OR char_length(note) <= 1000', name=op.f('ck_report_note_length')),
    sa.CheckConstraint('resolution_note IS NULL OR char_length(resolution_note) <= 1000', name=op.f('ck_report_resolution_note_length')),
    sa.ForeignKeyConstraint(['reporter_account_id'], ['account.id'], name=op.f('fk_report_reporter_account_id_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report'))
    )
    op.create_index('ix_report_status_created_at', 'report', ['status', 'created_at'], unique=False)
    op.create_index('uq_report_open_per_reporter', 'report', ['reporter_account_id', 'subject_kind', 'subject_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.add_column('account', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('account', sa.Column('suspension_reason', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###
    op.drop_constraint('role_allowed', 'account', type_='check')
    # NOT VALID now, VALIDATE after the transaction commits: adding a check
    # normally scans the table while blocking writes, and validating inside the
    # same transaction would hold that lock anyway (Squawk, D-050).
    checks = (
        ("ck_account_role_allowed", "role IN ('brand', 'creator', 'admin')"),
        (
            "ck_account_suspension_reason_allowed",
            "suspension_reason IS NULL OR suspension_reason IN "
            "('fake_profile', 'spam', 'abuse', 'non_payment', 'other')",
        ),
        (
            "ck_account_suspension_has_reason",
            "(suspended_at IS NULL) = (suspension_reason IS NULL)",
        ),
    )
    for name, condition in checks:
        op.execute(f"ALTER TABLE account ADD CONSTRAINT {name} CHECK ({condition}) NOT VALID")
    op.execute(
        "CREATE TRIGGER admin_action_no_update_or_delete "
        "BEFORE UPDATE OR DELETE ON admin_action "
        "FOR EACH ROW EXECUTE FUNCTION append_only_refuse_change()"
    )
    op.execute(
        "CREATE TRIGGER admin_action_no_truncate "
        "BEFORE TRUNCATE ON admin_action "
        "FOR EACH STATEMENT EXECUTE FUNCTION append_only_refuse_change()"
    )
    with op.get_context().autocommit_block():
        for name, _ in checks:
            op.execute(f"ALTER TABLE account VALIDATE CONSTRAINT {name}")


def downgrade() -> None:
    admins = op.get_bind().execute(
        sa.text("SELECT count(*) FROM account WHERE role = 'admin'")
    ).scalar_one()
    if admins:
        raise RuntimeError(
            f"{admins} admin account(s) exist. Remove them deliberately before "
            "downgrading; this migration will not orphan them."
        )
    op.drop_constraint('suspension_has_reason', 'account', type_='check')
    op.drop_constraint('suspension_reason_allowed', 'account', type_='check')
    op.drop_constraint('role_allowed', 'account', type_='check')
    op.create_check_constraint(
        'role_allowed', 'account', "role IN ('brand', 'creator')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'suspension_reason')
    op.drop_column('account', 'suspended_at')
    op.drop_index('uq_report_open_per_reporter', table_name='report', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_report_status_created_at', table_name='report')
    op.drop_table('report')
    op.drop_index('ix_admin_action_created_at', table_name='admin_action')
    op.drop_table('admin_action')
    # ### end Alembic commands ###
