"""add deal record checkpoints (D-060)

Two append-only tables for the daily Merkle root over every deal's latest
seal and the RFC 3161 timestamps on it. Both refuse UPDATE, DELETE and
TRUNCATE through one general trigger function that names the table it
guards; deal_record_entry keeps its own function, from its own migration.

Revision ID: 18aa2bc4cc78
Revises: a5f4c789f774
Create Date: 2026-09-26 23:26:40.329984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18aa2bc4cc78'
down_revision: Union[str, None] = 'a5f4c789f774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

APPEND_ONLY_TABLES = ("deal_record_checkpoint", "deal_record_timestamp")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_record_checkpoint',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('covers_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leaf_count', sa.Integer(), nullable=False),
    sa.Column('merkle_root', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('leaf_count >= 0', name=op.f('ck_deal_record_checkpoint_leaf_count_not_negative')),
    sa.CheckConstraint('octet_length(merkle_root) = 32', name=op.f('ck_deal_record_checkpoint_merkle_root_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_record_checkpoint')),
    sa.UniqueConstraint('covers_until', name='uq_deal_record_checkpoint_covers_until')
    )
    op.create_table('deal_record_timestamp',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('checkpoint_id', sa.UUID(), nullable=False),
    sa.Column('authority', sa.String(length=40), nullable=False),
    sa.Column('token', sa.LargeBinary(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("authority IN ('digicert', 'sectigo')", name=op.f('ck_deal_record_timestamp_authority_allowed')),
    sa.CheckConstraint('octet_length(token) > 0', name=op.f('ck_deal_record_timestamp_token_not_empty')),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['deal_record_checkpoint.id'], name=op.f('fk_deal_record_timestamp_checkpoint_id_deal_record_checkpoint'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_record_timestamp')),
    sa.UniqueConstraint('checkpoint_id', 'authority', name='uq_deal_record_timestamp_authority')
    )
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION append_only_refuse_change() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only: % refused', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$
        """
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_no_update_or_delete "
            f"BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION append_only_refuse_change()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate "
            f"BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION append_only_refuse_change()"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal_record_timestamp')
    op.drop_table('deal_record_checkpoint')
    # ### end Alembic commands ###
    # Dropping the tables dropped their triggers; the function is separate.
    op.execute("DROP FUNCTION append_only_refuse_change()")
