"""add account.adult_confirmed_at (D-086)

Adults only (approved by Adhi, 10 October 2026): a contract with a minor is
void in India and a minor's data needs verified parental consent
(docs/standards/legal.md section 3.10). Creating a profile now takes a date
of birth, checks it, and keeps only this: when the person confirmed they
are 18 or over. The date itself is never stored.

Nullable, no default: existing accounts were made before the rule, and
adding a nullable column rewrites nothing and locks only for an instant.

The downgrade drops the column, losing the confirmation times; they are a
record of a check, and the downgrade is only for undoing this release.

Revision ID: 5cf8639be443
Revises: e39beab4e841
Create Date: 2026-10-10 07:56:12.857838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf8639be443'
down_revision: Union[str, None] = 'e39beab4e841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('adult_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'adult_confirmed_at')
    # ### end Alembic commands ###
