"""add notification_preference (D-079)

How each person wants to be told things outside the app: quiet hours, a
daily digest, and what they muted (approved by Adhi in session, 8 October
2026). One row per account, written only when the person saves; no row means
the defaults, so no existing account needs a row and nothing is backfilled.

- account_id: ON DELETE CASCADE, a person's own settings go with them. Its
  unique constraint is also the index the foreign key needs.
- muted_types may hold only the types that can be muted: the urgent ones
  (memo_sent, proof_submitted, proof_revision_requested,
  payment_marked_paid) are refused by the database itself, not only by the
  API.
- A new, empty table, so its checks are added whole (Squawk, D-050).

The downgrade drops the table: the preferences are settings, not a record,
and everyone falls back to the defaults.

Revision ID: 636f06a7e2dc
Revises: b3172a361a61
Create Date: 2026-10-08 15:43:27.487701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '636f06a7e2dc'
down_revision: Union[str, None] = 'b3172a361a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preference',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('quiet_from', sa.Time(), nullable=True),
    sa.Column('quiet_until', sa.Time(), nullable=True),
    sa.Column('digest', sa.String(length=10), server_default=sa.text("'off'"), nullable=False),
    sa.Column('digest_hour', sa.SmallInteger(), server_default=sa.text('19'), nullable=False),
    sa.Column('muted_types', postgresql.ARRAY(sa.String(length=40)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("digest IN ('off', 'daily')", name=op.f('ck_notification_preference_digest_allowed')),
    sa.CheckConstraint("muted_types <@ ARRAY['application_received', 'application_withdrawn', 'memo_accepted', 'memo_declined', 'memo_change_requested', 'application_shortlisted', 'application_accepted', 'application_rejected', 'proof_approved', 'proof_auto_approved', 'memo_cancelled', 'payment_confirmed']::varchar[]", name=op.f('ck_notification_preference_muted_types_allowed')),
    sa.CheckConstraint('(quiet_from IS NULL) = (quiet_until IS NULL)', name=op.f('ck_notification_preference_quiet_hours_whole')),
    sa.CheckConstraint('digest_hour BETWEEN 0 AND 23', name=op.f('ck_notification_preference_digest_hour_valid')),
    sa.CheckConstraint('quiet_from IS NULL OR quiet_from <> quiet_until', name=op.f('ck_notification_preference_quiet_hours_not_empty')),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_notification_preference_account_id_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preference')),
    sa.UniqueConstraint('account_id', name=op.f('uq_notification_preference_account_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_preference')
    # ### end Alembic commands ###
