"""add invite_code and account_attribution (D-080)

How each account arrived, written once at sign-up, and the codes people
invite others with (approved by Adhi in session, 8 October 2026). Both
tables are new and empty; existing accounts get no row, and read as having
arrived before anybody asked. Nothing is backfilled.

- invite_code.account_id: ON DELETE CASCADE, a person's code is their own.
  Unique, which is also its index.
- account_attribution.account_id: ON DELETE CASCADE, how a person arrived is
  about them. Unique, which is also its index.
- account_attribution.invite_code_id: ON DELETE SET NULL, so an inviter
  leaving removes the link but not the fact that this account was invited
  (the source stays `invite`). Indexed for "who joined with my code".
- (source, created_at) is indexed for the admin's sign-ups by week.
- New, empty tables, so their checks and indexes are created whole (Squawk,
  D-050).

The downgrade refuses while any attribution exists: it cannot be recovered
once dropped (D-071), so losing it must be a deliberate act, not a rollback.

Revision ID: 8c960d1db341
Revises: 636f06a7e2dc
Create Date: 2026-10-08 15:48:05.547156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c960d1db341'
down_revision: Union[str, None] = '636f06a7e2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_code',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{8}$'", name=op.f('ck_invite_code_code_format')),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_invite_code_account_id_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_code')),
    sa.UniqueConstraint('account_id', name=op.f('uq_invite_code_account_id')),
    sa.UniqueConstraint('code', name=op.f('uq_invite_code_code'))
    )
    op.create_table('account_attribution',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('invite_code_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('campaign_tag', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("campaign_tag IS NULL OR campaign_tag ~ '^[a-z0-9-]{1,40}$'", name=op.f('ck_account_attribution_campaign_tag_format')),
    sa.CheckConstraint("invite_code_id IS NULL OR source = 'invite'", name=op.f('ck_account_attribution_code_means_invite')),
    sa.CheckConstraint("source IN ('invite', 'passport_link', 'instagram', 'whatsapp', 'event', 'search', 'other', 'not_given')", name=op.f('ck_account_attribution_source_allowed')),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_account_attribution_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invite_code_id'], ['invite_code.id'], name=op.f('fk_account_attribution_invite_code_id_invite_code'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_attribution')),
    sa.UniqueConstraint('account_id', name=op.f('uq_account_attribution_account_id'))
    )
    op.create_index('ix_account_attribution_invite_code_id', 'account_attribution', ['invite_code_id'], unique=False)
    op.create_index('ix_account_attribution_source_created_at', 'account_attribution', ['source', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    recorded = op.get_bind().execute(
        sa.text("SELECT count(*) FROM account_attribution")
    ).scalar_one()
    if recorded:
        raise RuntimeError(
            f"{recorded} accounts have their arrival recorded. It can never be "
            "recovered once dropped, so this downgrade will not run."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_attribution_source_created_at', table_name='account_attribution')
    op.drop_index('ix_account_attribution_invite_code_id', table_name='account_attribution')
    op.drop_table('account_attribution')
    op.drop_table('invite_code')
    # ### end Alembic commands ###
