"""add deal record (D-057)

One append-only table, and the schema's first trigger: the database itself
refuses UPDATE, DELETE and TRUNCATE on it, so a bug, a script or a hand-edit
fails loudly instead of rewriting a deal's history.

Revision ID: a5f4c789f774
Revises: d523d35ee32f
Create Date: 2026-09-26 20:23:45.109833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5f4c789f774'
down_revision: Union[str, None] = 'd523d35ee32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_record_entry',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('deal_memo_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('actor_role', sa.String(length=10), nullable=False),
    sa.Column('actor_account_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_hash', sa.LargeBinary(), nullable=False),
    sa.Column('entry_hash', sa.LargeBinary(), nullable=False),
    sa.CheckConstraint("(actor_role = 'system') = (actor_account_id IS NULL)", name=op.f('ck_deal_record_entry_actor_account_matches_role')),
    sa.CheckConstraint("(sequence = 1) = (previous_hash = '\\x0000000000000000000000000000000000000000000000000000000000000000'::bytea)", name=op.f('ck_deal_record_entry_genesis_only_first')),
    sa.CheckConstraint("actor_role IN ('brand', 'creator', 'system')", name=op.f('ck_deal_record_entry_actor_role_allowed')),
    sa.CheckConstraint("jsonb_typeof(facts) = 'object'", name=op.f('ck_deal_record_entry_facts_is_object')),
    sa.CheckConstraint("kind IN ('record_started', 'memo_sent', 'memo_change_requested', 'memo_accepted', 'memo_declined', 'memo_cancelled', 'proof_submitted', 'proof_approved', 'proof_auto_approved', 'proof_revision_requested', 'payment_opened', 'payment_marked_paid', 'payment_confirmed', 'dispute_opened', 'dispute_entry_added', 'dispute_closed')", name=op.f('ck_deal_record_entry_kind_allowed')),
    sa.CheckConstraint('octet_length(entry_hash) = 32', name=op.f('ck_deal_record_entry_entry_hash_length')),
    sa.CheckConstraint('octet_length(previous_hash) = 32', name=op.f('ck_deal_record_entry_previous_hash_length')),
    sa.CheckConstraint('sequence >= 1', name=op.f('ck_deal_record_entry_sequence_positive')),
    sa.ForeignKeyConstraint(['deal_memo_id'], ['deal_memo.id'], name=op.f('fk_deal_record_entry_deal_memo_id_deal_memo'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_record_entry')),
    sa.UniqueConstraint('deal_memo_id', 'sequence', name='uq_deal_record_entry_sequence')
    )
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION deal_record_entry_refuse_change() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'deal_record_entry is append-only: % refused', TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER deal_record_entry_no_update_or_delete "
        "BEFORE UPDATE OR DELETE ON deal_record_entry "
        "FOR EACH ROW EXECUTE FUNCTION deal_record_entry_refuse_change()"
    )
    op.execute(
        "CREATE TRIGGER deal_record_entry_no_truncate "
        "BEFORE TRUNCATE ON deal_record_entry "
        "FOR EACH STATEMENT EXECUTE FUNCTION deal_record_entry_refuse_change()"
    )


def downgrade() -> None:
    # Dropping the table drops its triggers with it; the function is separate.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal_record_entry')
    op.execute("DROP FUNCTION deal_record_entry_refuse_change()")
    # ### end Alembic commands ###
