"""add proof_file_reading (D-070)

What a cleaned proof screenshot said, read by Claude and checked by us, one
row per file, and a deal record kind, `proof_results_read`, that seals it
(approved by Adhi in session, 1 October 2026).

The table is new and empty, so its checks are added whole; only existing
tables need NOT VALID (Squawk, D-050). The record's kind check is widened as
D-066 did it: the new check added NOT VALID beside the old, the old dropped,
the new renamed into its place, then validated after the transaction
commits, so no moment admits an unknown kind and no scan blocks writes.

Alembic compares neither CHECK constraints nor this kind list, so that part
is written by hand.

The downgrade refuses while any `proof_results_read` entry exists: the record
is append-only, so those entries can never be removed, and readings they
seal must not vanish from under them.

Revision ID: b3172a361a61
Revises: 608541cc4a4e
Create Date: 2026-10-01 15:19:39.208545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3172a361a61'
down_revision: Union[str, None] = '608541cc4a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

OLD_KINDS = (
    "record_started",
    "memo_sent",
    "memo_change_requested",
    "memo_accepted",
    "memo_declined",
    "memo_cancelled",
    "proof_submitted",
    "proof_approved",
    "proof_auto_approved",
    "proof_revision_requested",
    "proof_file_cleaned",
    "payment_opened",
    "payment_marked_paid",
    "payment_confirmed",
    "dispute_opened",
    "dispute_entry_added",
    "dispute_closed",
)
NEW_KINDS = OLD_KINDS[:11] + ("proof_results_read",) + OLD_KINDS[11:]

NAME = "ck_deal_record_entry_kind_allowed"
STAGING = "ck_deal_record_entry_kind_allowed_next"


def _in(kinds: tuple[str, ...]) -> str:
    return "kind IN (" + ", ".join(f"'{kind}'" for kind in kinds) + ")"


def _set_kinds(kinds: tuple[str, ...]) -> None:
    op.execute(
        f"ALTER TABLE deal_record_entry ADD CONSTRAINT {STAGING} "
        f"CHECK ({_in(kinds)}) NOT VALID"
    )
    op.execute(f"ALTER TABLE deal_record_entry DROP CONSTRAINT {NAME}")
    op.execute(f"ALTER TABLE deal_record_entry RENAME CONSTRAINT {STAGING} TO {NAME}")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proof_file_reading',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('proof_file_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('handle', sa.String(length=30), nullable=True),
    sa.Column('post_date', sa.Date(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('reach', sa.BigInteger(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('saves', sa.BigInteger(), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('abbreviated', postgresql.ARRAY(sa.String(length=20)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('handle_matches', sa.Boolean(), nullable=True),
    sa.Column('date_within_deal', sa.Boolean(), nullable=True),
    sa.Column('numbers_consistent', sa.Boolean(), nullable=True),
    sa.Column('stated_followers', sa.Integer(), nullable=True),
    sa.Column('stated_average_views', sa.Integer(), nullable=True),
    sa.Column('creator_marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_note', sa.String(length=500), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'failed') = (failure IS NOT NULL)", name=op.f('ck_proof_file_reading_failed_has_reason')),
    sa.CheckConstraint("(status = 'read' AND (views IS NOT NULL OR reach IS NOT NULL OR impressions IS NOT NULL OR likes IS NOT NULL OR comments IS NOT NULL OR saves IS NOT NULL OR shares IS NOT NULL)) OR (status <> 'read' AND views IS NULL AND reach IS NULL AND impressions IS NULL AND likes IS NULL AND comments IS NULL AND saves IS NULL AND shares IS NULL)", name=op.f('ck_proof_file_reading_numbers_only_when_read')),
    sa.CheckConstraint("abbreviated <@ ARRAY['views', 'reach', 'impressions', 'likes', 'comments', 'saves', 'shares']::varchar[]", name=op.f('ck_proof_file_reading_abbreviated_allowed')),
    sa.CheckConstraint("failure IS NULL OR failure IN ('refusal', 'max_tokens', 'api_error', 'invalid_answer', 'image_too_large')", name=op.f('ck_proof_file_reading_failure_allowed')),
    sa.CheckConstraint("platform IS NULL OR platform IN ('instagram', 'youtube', 'other')", name=op.f('ck_proof_file_reading_platform_allowed')),
    sa.CheckConstraint("status IN ('read', 'no_numbers', 'failed')", name=op.f('ck_proof_file_reading_status_allowed')),
    sa.CheckConstraint('(views IS NULL OR views >= 0) AND (reach IS NULL OR reach >= 0) AND (impressions IS NULL OR impressions >= 0) AND (likes IS NULL OR likes >= 0) AND (comments IS NULL OR comments >= 0) AND (saves IS NULL OR saves >= 0) AND (shares IS NULL OR shares >= 0)', name=op.f('ck_proof_file_reading_numbers_not_negative')),
    sa.CheckConstraint('attempts >= 1', name=op.f('ck_proof_file_reading_attempts_positive')),
    sa.CheckConstraint('creator_note IS NULL OR creator_marked_at IS NOT NULL', name=op.f('ck_proof_file_reading_note_has_mark')),
    sa.CheckConstraint('input_tokens >= 0 AND output_tokens >= 0', name=op.f('ck_proof_file_reading_tokens_not_negative')),
    sa.CheckConstraint('stated_average_views IS NULL OR stated_average_views >= 0', name=op.f('ck_proof_file_reading_stated_average_views_valid')),
    sa.CheckConstraint('stated_followers IS NULL OR stated_followers >= 0', name=op.f('ck_proof_file_reading_stated_followers_valid')),
    sa.ForeignKeyConstraint(['proof_file_id'], ['proof_file.id'], name=op.f('fk_proof_file_reading_proof_file_id_proof_file'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proof_file_reading')),
    sa.UniqueConstraint('proof_file_id', name=op.f('uq_proof_file_reading_proof_file_id'))
    )
    # ### end Alembic commands ###
    _set_kinds(NEW_KINDS)
    with op.get_context().autocommit_block():
        op.execute(f"ALTER TABLE deal_record_entry VALIDATE CONSTRAINT {NAME}")


def downgrade() -> None:
    sealed = op.get_bind().execute(
        sa.text("SELECT count(*) FROM deal_record_entry WHERE kind = 'proof_results_read'")
    ).scalar_one()
    if sealed:
        raise RuntimeError(
            f"{sealed} proof_results_read record entries exist. The record is "
            "append-only, so they cannot be removed; this downgrade will not run."
        )
    _set_kinds(OLD_KINDS)
    with op.get_context().autocommit_block():
        op.execute(f"ALTER TABLE deal_record_entry VALIDATE CONSTRAINT {NAME}")
    op.drop_table('proof_file_reading')
