"""add payment notification types

Revision ID: c3b81e47af20
Revises: f72f456249a6
Create Date: 2026-09-20 23:58:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c3b81e47af20'
down_revision: Union[str, None] = 'f72f456249a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CONSTRAINT = "ck_notification_type_allowed"

# Two new types, both of which the app actually sends today: the creator is
# told the brand says it has paid, and the brand is told the creator confirmed
# it arrived. The reminder types from D-029 are not added here, because
# nothing sends them until a job runner is chosen and a CHECK constraint
# listing values nobody writes is just a claim we have not kept.
OLD_TYPES = ('application_received', 'application_withdrawn', 'memo_accepted', 'memo_declined', 'memo_change_requested', 'proof_submitted', 'application_shortlisted', 'application_accepted', 'application_rejected', 'memo_sent', 'proof_approved', 'proof_auto_approved', 'proof_revision_requested', 'memo_cancelled')
NEW_TYPES = ('application_received', 'application_withdrawn', 'memo_accepted', 'memo_declined', 'memo_change_requested', 'proof_submitted', 'application_shortlisted', 'application_accepted', 'application_rejected', 'memo_sent', 'proof_approved', 'proof_auto_approved', 'proof_revision_requested', 'payment_marked_paid', 'memo_cancelled', 'payment_confirmed')


def _condition(values: tuple) -> str:
    return f"notification_type IN {tuple(values)}"


def upgrade() -> None:
    # Hand-written, not autogenerated: alembic does not notice a changed
    # CHECK constraint. op.f() on BOTH the drop and the create, because
    # without it the naming convention prefixes an already-prefixed name and
    # leaves the table half-migrated.
    op.drop_constraint(op.f(CONSTRAINT), "notification", type_="check")
    op.create_check_constraint(op.f(CONSTRAINT), "notification", _condition(NEW_TYPES))


def downgrade() -> None:
    # Rows carrying a removed type would fail the older constraint, so they
    # go first. Nothing else can reference them: a notification is a leaf.
    op.execute(
        "DELETE FROM notification WHERE notification_type IN "
        "('payment_marked_paid', 'payment_confirmed')"
    )
    op.drop_constraint(op.f(CONSTRAINT), "notification", type_="check")
    op.create_check_constraint(op.f(CONSTRAINT), "notification", _condition(OLD_TYPES))
