"""add proof files (D-065)

A proof may now be files as well as, or instead of, a link: `proof_file`
holds what we know about each screenshot or photo in S3, and
`deliverable_proof.content_url` becomes optional.

The table is new and empty, so its checks are added whole; only existing
tables need NOT VALID (Squawk, D-050). Dropping NOT NULL is a catalogue change
and takes no scan.

The downgrade refuses while any proof file exists: dropping the table would
throw away what the deal record's fingerprints point to and leave the files
in S3 with nothing naming them. It also refuses while a proof has no link,
since restoring NOT NULL under one would fail halfway.

Revision ID: c45a9831e0c9
Revises: 0942f3ef82c3
Create Date: 2026-10-01 02:10:35.969227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45a9831e0c9'
down_revision: Union[str, None] = '0942f3ef82c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proof_file',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('deal_memo_id', sa.UUID(), nullable=False),
    sa.Column('proof_id', sa.UUID(), nullable=True),
    sa.Column('uploader_account_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('clean_key', sa.String(length=200), nullable=True),
    sa.Column('clean_sha256', sa.String(length=64), nullable=True),
    sa.Column('clean_size_bytes', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=40), nullable=True),
    sa.Column('attached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleaned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'cleaned') = (clean_key IS NOT NULL AND clean_sha256 IS NOT NULL AND clean_size_bytes IS NOT NULL AND cleaned_at IS NOT NULL)", name=op.f('ck_proof_file_cleaned_has_copy')),
    sa.CheckConstraint("(status = 'rejected') = (rejection_reason IS NOT NULL)", name=op.f('ck_proof_file_rejected_has_reason')),
    sa.CheckConstraint("clean_sha256 IS NULL OR clean_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_proof_file_clean_sha256_hex')),
    sa.CheckConstraint("content_type IN ('image/jpeg', 'image/png', 'image/webp')", name=op.f('ck_proof_file_content_type_allowed')),
    sa.CheckConstraint("rejection_reason IS NULL OR rejection_reason IN ('fingerprint_mismatch', 'not_an_image', 'too_many_pixels', 'missing')", name=op.f('ck_proof_file_rejection_reason_allowed')),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_proof_file_sha256_hex')),
    sa.CheckConstraint("status <> 'pending' OR (proof_id IS NULL AND attached_at IS NULL)", name=op.f('ck_proof_file_pending_is_unattached')),
    sa.CheckConstraint("status IN ('pending', 'attached', 'cleaned', 'rejected')", name=op.f('ck_proof_file_status_allowed')),
    sa.CheckConstraint("status NOT IN ('attached', 'cleaned') OR (proof_id IS NOT NULL AND attached_at IS NOT NULL)", name=op.f('ck_proof_file_attached_has_proof')),
    sa.CheckConstraint('size_bytes BETWEEN 1 AND 10485760', name=op.f('ck_proof_file_size_in_range')),
    sa.ForeignKeyConstraint(['deal_memo_id'], ['deal_memo.id'], name=op.f('fk_proof_file_deal_memo_id_deal_memo'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proof_id'], ['deliverable_proof.id'], name=op.f('fk_proof_file_proof_id_deliverable_proof'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploader_account_id'], ['account.id'], name=op.f('fk_proof_file_uploader_account_id_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proof_file')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_proof_file_storage_key'))
    )
    op.create_index('ix_proof_file_attached_queue', 'proof_file', ['attached_at'], unique=False, postgresql_where=sa.text("status = 'attached'"))
    op.create_index('ix_proof_file_deal_memo_id', 'proof_file', ['deal_memo_id'], unique=False)
    op.create_index('ix_proof_file_proof_id', 'proof_file', ['proof_id'], unique=False)
    op.create_index('ix_proof_file_uploader_account_id', 'proof_file', ['uploader_account_id'], unique=False)
    op.alter_column('deliverable_proof', 'content_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    if connection.execute(sa.text("SELECT EXISTS (SELECT 1 FROM proof_file)")).scalar():
        raise RuntimeError(
            "Refusing to downgrade: proof files exist. Dropping proof_file would "
            "orphan them in S3 and break what the deal record points to."
        )
    if connection.execute(
        sa.text("SELECT EXISTS (SELECT 1 FROM deliverable_proof WHERE content_url IS NULL)")
    ).scalar():
        raise RuntimeError("Refusing to downgrade: a proof has no link to restore NOT NULL on.")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliverable_proof', 'content_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_index('ix_proof_file_uploader_account_id', table_name='proof_file')
    op.drop_index('ix_proof_file_proof_id', table_name='proof_file')
    op.drop_index('ix_proof_file_deal_memo_id', table_name='proof_file')
    op.drop_index('ix_proof_file_attached_queue', table_name='proof_file', postgresql_where=sa.text("status = 'attached'"))
    op.drop_table('proof_file')
    # ### end Alembic commands ###
