"""add creator channels and rate card

Revision ID: d523d35ee32f
Revises: a1c4e9d27b30
Create Date: 2026-09-25 18:30:16.368213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd523d35ee32f'
down_revision: Union[str, None] = 'a1c4e9d27b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_channel',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('profile_url', sa.String(length=300), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('average_views', sa.Integer(), nullable=True),
    sa.Column('figures_as_of', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('instagram', 'youtube')", name=op.f('ck_creator_channel_platform_allowed')),
    sa.CheckConstraint("profile_url LIKE 'https://%%'", name=op.f('ck_creator_channel_profile_url_https')),
    sa.CheckConstraint('average_views IS NULL OR average_views >= 0', name=op.f('ck_creator_channel_average_views_not_negative')),
    sa.CheckConstraint('followers >= 0', name=op.f('ck_creator_channel_followers_not_negative')),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], name=op.f('fk_creator_channel_creator_id_creator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creator_channel')),
    sa.UniqueConstraint('creator_id', 'platform', name='uq_creator_channel_platform')
    )
    op.create_table('creator_package',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('delivery_days', sa.SmallInteger(), nullable=False),
    sa.Column('usage_rights_days', sa.Integer(), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency = 'INR'", name=op.f('ck_creator_package_currency_allowed')),
    sa.CheckConstraint("format IN ('post', 'reel', 'story', 'short', 'video', 'live', 'other')", name=op.f('ck_creator_package_format_allowed')),
    sa.CheckConstraint("platform IN ('instagram', 'youtube')", name=op.f('ck_creator_package_platform_allowed')),
    sa.CheckConstraint('char_length(btrim(title)) > 0', name=op.f('ck_creator_package_title_not_blank')),
    sa.CheckConstraint('delivery_days BETWEEN 1 AND 90', name=op.f('ck_creator_package_delivery_days_range')),
    sa.CheckConstraint('description IS NULL OR char_length(description) <= 500', name=op.f('ck_creator_package_description_length')),
    sa.CheckConstraint('position BETWEEN 0 AND 19', name=op.f('ck_creator_package_position_range')),
    sa.CheckConstraint('price_paise > 0', name=op.f('ck_creator_package_price_positive')),
    sa.CheckConstraint('usage_rights_days IS NULL OR usage_rights_days BETWEEN 0 AND 3650', name=op.f('ck_creator_package_usage_rights_days_range')),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], name=op.f('fk_creator_package_creator_id_creator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creator_package'))
    )
    op.create_index('ix_creator_package_creator_position', 'creator_package', ['creator_id', 'position'], unique=False)
    op.add_column('creator', sa.Column('rate_card_public_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creator', 'rate_card_public_at')
    op.drop_index('ix_creator_package_creator_position', table_name='creator_package')
    op.drop_table('creator_package')
    op.drop_table('creator_channel')
    # ### end Alembic commands ###
