"""add creator_upi (D-085)

Where a creator is paid: their UPI ID, so the brand on a deal can pay them
through a pay link instead of copying an ID by hand (item 32, approved by
Adhi; built in session 10 October 2026). The money still goes from the
brand's bank to the creator's bank; nothing here holds or moves it.

A new, empty table, so its checks and keys are created whole.

- One row per creator (unique), written only when they add a UPI ID.
- ON DELETE CASCADE from creator: a person's own detail goes with them.
- The ID's format, and that its name part is not a mobile number (which
  would give the number away), are checks, so no path can store either.
- The consent is the row's `consented_at` and `notice_version`, given
  again on every change.

No index beyond the unique key: every read is by creator.

The downgrade refuses while any row exists. Each row is a record of a
person's consent, which the DPDP Act may require us to show; it is not
dropped as a side effect of a rollback (database.md section 6).

Revision ID: e39beab4e841
Revises: 2c3bf71783d2
Create Date: 2026-10-10 07:36:30.928897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39beab4e841'
down_revision: Union[str, None] = '2c3bf71783d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_upi',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('upi_id', sa.String(length=128), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notice_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("split_part(upi_id, '@', 1) !~ '^(91)?[6-9][0-9]{9}$'", name=op.f('ck_creator_upi_upi_id_not_a_phone_number')),
    sa.CheckConstraint("upi_id ~ '^[a-z0-9._-]{2,64}@[a-z][a-z0-9]{1,63}$'", name=op.f('ck_creator_upi_upi_id_format')),
    sa.CheckConstraint('char_length(btrim(notice_version)) > 0', name=op.f('ck_creator_upi_notice_version_not_blank')),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], name=op.f('fk_creator_upi_creator_id_creator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creator_upi')),
    sa.UniqueConstraint('creator_id', name=op.f('uq_creator_upi_creator_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    rows = op.get_bind().execute(sa.text("SELECT count(*) FROM creator_upi")).scalar_one()
    if rows:
        raise RuntimeError(
            f"{rows} creator UPI ID(s) exist, each with the consent it was given "
            "under. Remove them deliberately before downgrading; this migration "
            "will not."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creator_upi')
    # ### end Alembic commands ###
