"""add account_block (item 59)

One account blocking another (docs/standards/trust-and-safety.md rule 7;
approved by Adhi, "approve all", 10 October 2026). A new, empty table, so
its checks and indexes are created whole.

- One row per (blocker, blocked) pair, unique; an account cannot block
  itself.
- ON DELETE CASCADE on both accounts: a block means nothing once either
  account is gone.
- The unique pair serves "whom did I block?"; a second index serves "has
  anyone blocked me?", which every search and matching query asks.

The downgrade refuses while any block exists: each is a person's choice not
to be contacted, and a rollback must not silently undo it.

Revision ID: e591b300cca7
Revises: 5cf8639be443
Create Date: 2026-10-10 21:25:37.236415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e591b300cca7'
down_revision: Union[str, None] = '5cf8639be443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_block',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('blocker_account_id', sa.UUID(), nullable=False),
    sa.Column('blocked_account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blocker_account_id <> blocked_account_id', name=op.f('ck_account_block_not_oneself')),
    sa.ForeignKeyConstraint(['blocked_account_id'], ['account.id'], name=op.f('fk_account_block_blocked_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_account_id'], ['account.id'], name=op.f('fk_account_block_blocker_account_id_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_block')),
    sa.UniqueConstraint('blocker_account_id', 'blocked_account_id', name='uq_account_block_pair')
    )
    op.create_index('ix_account_block_blocked_account_id', 'account_block', ['blocked_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    blocks = op.get_bind().execute(sa.text("SELECT count(*) FROM account_block")).scalar_one()
    if blocks:
        raise RuntimeError(
            f"{blocks} block(s) exist, each a person's choice not to be "
            "contacted. Remove them deliberately before downgrading; this "
            "migration will not."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_block_blocked_account_id', table_name='account_block')
    op.drop_table('account_block')
    # ### end Alembic commands ###
