"""add creator.booked_until (D-083)

"Booked until 20 Nov": the last Tamil Nadu day a creator is not taking new
work (approved by Adhi in session, 8 October 2026). Nullable, no default:
NULL means taking work, so every existing creator stays exactly as they are,
and adding a nullable column without a default rewrites nothing and holds its
lock only for an instant.

No CHECK: the rule (from today, at most a year ahead) is relative to the day
it is set, which a CHECK cannot read; the service enforces it. No index: the
column is only ever a filter on rows already picked by search's and
matching's own conditions, never the way into the table.

The downgrade drops the column. What it held is a short-lived preference the
creator can set again, not a record (database.md section 6).

Revision ID: f74cbe0d42c9
Revises: 8c960d1db341
Create Date: 2026-10-08 21:33:46.893057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74cbe0d42c9'
down_revision: Union[str, None] = '8c960d1db341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator', sa.Column('booked_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creator', 'booked_until')
    # ### end Alembic commands ###
